name = "glory"
compatibility_date = "2026-05-13"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist/client"
[[d1_databases]]
binding = "DB"
database_name = "driveschool-pro"
database_id = "your-database-id-here"
