name = "glory"
compatibility_date = "2026-05-13"
pages_build_output_dir = "./dist/client"

[[d1_databases]]
binding = "DB"
database_name = "driveschool-pro"
database_id = "1daf6984-59c5-402e-b3fc-5ff438034c94"
