/**
 * Minimal postbuild script for Cloudflare Pages deployment
 * Ensures the wrangler.json generated by the build is compatible with Pages
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const wranglerFile = join(__dirname, "..", "dist", "client", "wrangler.json");

console.log('🔧 Post-build: Checking wrangler.json...');

if (!existsSync(wranglerFile)) {
  console.log('⚠️  No wrangler.json found in dist/client/ - build may use different structure');
  process.exit(0);
}

const config = JSON.parse(readFileSync(wranglerFile, "utf-8"));

// Pages doesn't support both 'main' and 'pages_build_output_dir' together
// Remove 'main' if both exist
if (config.main && config.pages_build_output_dir) {
  console.log('   Removing "main" field (conflicts with pages_build_output_dir)');
  delete config.main;
}

// Ensure D1 database binding
if (!config.d1_databases || !Array.isArray(config.d1_databases)) {
  config.d1_databases = [];
}

const dbBinding = config.d1_databases.find(b => b.binding === 'DB');
if (!dbBinding) {
  config.d1_databases.push({
    binding: 'DB',
    database_name: 'driveschool-pro',
    database_id: '1daf6984-59c5-402e-b3fc-5ff438034c94'
  });
  console.log('   Added D1 database binding');
}

writeFileSync(wranglerFile, JSON.stringify(config, null, 2));
console.log('✅ Post-build complete!');
